name: CI

on:
  push:
    branches:
      - emad_ezz_auth

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          docker build -t ezzops/khoyoutbackend:${{ github.sha }} .
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ezzops --password-stdin
      - name: Docker slim
        uses: kitabisa/docker-slim-action@v1
        env:
             DSLIM_HTTP_PROBE: false
        with:
              target: ezzops/khoyoutbackend:${{ github.sha }}
              tag: "slim"
      - run: docker image push ezzops/khoyoutbackend:${{ github.sha }}

  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server and execute commands
        uses: appleboy/ssh-action@master
        with:
            host: oniverse.xyz
            username: root
            password: ${{ secrets.Node_Pass }}
            script: |
              container_id=$(docker ps --format "{{.ID}}")
              docker logs $container_id > logs__khoyoutbackend$(date +%Y%m%d).log
              docker stop $(docker ps -aq)
              docker rm $(docker ps -aq)
              docker rmi $(docker images -q)
              docker run -d --restart=unless-stopped -p 3005:3005 ezzops/khoyoutbackend:${{ github.sha }}